### ISSUE TITLE
Détecter efficacement la couleur d'un mélanome

### ISSUE THREAD

**Issue by hwadii** [hwadii/melanoma-detection#1]
Nous avons avancé ce week-end sur le projet. Nous rencontrons toujours des problèmes pour détecter correctement la couleur d'un mélanome donné.
Nous avons rajouté un fichier `masks.js` qui contient les différentes couleurs possibles pour un mélanome et en utilisant les intervalles de HSV utilisés dans le PFE mais ces couleurs n'ont pas l'air d'être exactes.
Ce [guide](https://i.stack.imgur.com/gyuw4.png) semble être utile pour trouver les bons intervalles. Mais avez-vous des conseils à nous donner afin de trouver le meilleur intervalle possible pour une couleur, par exemple _light brown_ ?
Nous espérons trouver une solution cette semaine afin de passer à l'étape de la symétrie.

**Comment by agusbudi** [comment]
Oui, les intervalles de HSV utilisés dans le PFE ne sont pas correct. Essayer de cherche la couleur RGB ici (par exemple light brown) : https://rgb.to/color/10170/light-brown

Après cela, aller ici: https://alloyui.com/examples/color-picker/hsv pour trouver _lowerbound_ et _upperbound_ appropriée (essayer de copier la valeur HEX pour le trouver).

**Comment by hwadii** [comment]
Merci, je vais utiliser ces sites.
